var specifics_array = new Array();
specifics_values_array = new Array();
specifics_values_array.push('BIG');
specifics_values_array.push('Geomag');
specifics_values_array.push('Kawada');
specifics_values_array.push('Kawada - nanoblock');
specifics_values_array.push('Kinetic');
specifics_values_array.push('Kinetic Sand');
specifics_values_array.push('Londji');
specifics_values_array.push('Maya');
specifics_values_array.push('Meccano');
specifics_values_array.push('Mega Bloks');
specifics_values_array.push('Micki');
specifics_values_array.push('Nano Block');
specifics_values_array.push('Nanoblock');
specifics_values_array.push('PowerUp');
specifics_values_array.push('Smart Games');
specifics_values_array.push('Sparkle T');
specifics_values_array.push('ThinkFun');
specifics_values_array.push('Waba Fun');
object_specific = {'title':'Brand','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Pink');
specifics_values_array.push('White');
object_specific = {'title':'Colour','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('1990s');
object_specific = {'title':'Era','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Boys & Girls');
object_specific = {'title':'Gender','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('010');
specifics_values_array.push('0871772003311');
specifics_values_array.push('1001');
specifics_values_array.push('1006');
specifics_values_array.push('150-101');
specifics_values_array.push('150-201');
specifics_values_array.push('150-301');
specifics_values_array.push('333');
specifics_values_array.push('362');
specifics_values_array.push('500-002');
specifics_values_array.push('5000');
specifics_values_array.push('5040');
specifics_values_array.push('5050');
specifics_values_array.push('6701');
specifics_values_array.push('7020');
specifics_values_array.push('NB-014');
specifics_values_array.push('NB-015');
specifics_values_array.push('NB-016');
specifics_values_array.push('NB-017');
specifics_values_array.push('NB-018');
specifics_values_array.push('NBC-020');
specifics_values_array.push('NBC-021');
specifics_values_array.push('NBC-022');
specifics_values_array.push('NBC-033');
specifics_values_array.push('NBC-086');
specifics_values_array.push('NBC-092');
specifics_values_array.push('NBC-096');
specifics_values_array.push('NBC-111');
specifics_values_array.push('NBC-112');
specifics_values_array.push('NBC-113');
specifics_values_array.push('NBC-114');
specifics_values_array.push('NBCC-001');
specifics_values_array.push('NBC_004');
specifics_values_array.push('NBC_031');
specifics_values_array.push('NBC_098');
specifics_values_array.push('NBC_099');
specifics_values_array.push('NBC_100');
specifics_values_array.push('NBC_104');
specifics_values_array.push('NBC_105');
specifics_values_array.push('NBC_106');
specifics_values_array.push('NBC_120');
specifics_values_array.push('NBH-004');
specifics_values_array.push('NBH-005');
specifics_values_array.push('NBH-008');
specifics_values_array.push('NBH-009');
specifics_values_array.push('NBH-010');
specifics_values_array.push('NBH-030');
specifics_values_array.push('NBH-033');
specifics_values_array.push('NBH-052');
specifics_values_array.push('NBH_055');
specifics_values_array.push('NBH_056');
specifics_values_array.push('NBH_057');
specifics_values_array.push('NBH_065');
specifics_values_array.push('NBH_066');
specifics_values_array.push('NBH_072');
specifics_values_array.push('NBH_073');
specifics_values_array.push('NBH_075');
specifics_values_array.push('NBM-001');
specifics_values_array.push('NBM-003');
specifics_values_array.push('NBM-006');
specifics_values_array.push('SG 011');
specifics_values_array.push('SG 440US');
object_specific = {'title':'MPN','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Mixed Lot');
specifics_values_array.push('Molding Tool Kit');
specifics_values_array.push('Sand');
specifics_values_array.push('Spinning Top');
object_specific = {'title':'Product Type','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('1');
specifics_values_array.push('critters');
object_specific = {'title':'Quantity','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('5+ years');
object_specific = {'title':'Recommended Age Range','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Barbie');
specifics_values_array.push('Challenger Series');
specifics_values_array.push('Critters');
specifics_values_array.push('Deluxe');
specifics_values_array.push('Dinosaurs');
specifics_values_array.push('Free Build Set');
specifics_values_array.push('GEOMAG PANELS GLOW');
specifics_values_array.push('Insects');
specifics_values_array.push('mini collection series - Holiday');
specifics_values_array.push('mini collection series - Sea Creatures');
specifics_values_array.push('Musical Instruments');
specifics_values_array.push('Musicals');
specifics_values_array.push('Peanuts');
specifics_values_array.push('Site');
specifics_values_array.push('Sites to see');
object_specific = {'title':'Theme','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('019275010010');
specifics_values_array.push('019275010065');
specifics_values_array.push('019275050009');
specifics_values_array.push('019275050504');
specifics_values_array.push('019275067014');
specifics_values_array.push('019275070205');
specifics_values_array.push('0433599213528');
object_specific = {'title':'UPC','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
