var specifics_array = new Array();
specifics_values_array = new Array();
specifics_values_array.push('A-DATA');
specifics_values_array.push('Bosch');
specifics_values_array.push('Coast');
specifics_values_array.push('Cygnett');
specifics_values_array.push('Energizer');
specifics_values_array.push('Laser');
specifics_values_array.push('Lexar');
specifics_values_array.push('mophie');
specifics_values_array.push('Nintendo');
specifics_values_array.push('SanDisk');
specifics_values_array.push('Stanley');
specifics_values_array.push('Unbranded/Generic');
specifics_values_array.push('Verbatim');
specifics_values_array.push('Western Digital');
specifics_values_array.push('Xmini');
object_specific = {'title':'Brand','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('1100 mAh');
specifics_values_array.push('11000mAh');
specifics_values_array.push('32 GB');
specifics_values_array.push('4000mAh');
object_specific = {'title':'Capacity','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Class 10');
object_specific = {'title':'Class','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Black');
specifics_values_array.push('White');
object_specific = {'title':'Colour','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('For Apple');
object_specific = {'title':'Compatible Brand','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('For iPhone 6');
specifics_values_array.push('For iPhone 6 Plus');
specifics_values_array.push('For Samsung');
specifics_values_array.push('iPhone 6');
specifics_values_array.push('Universal');
object_specific = {'title':'Compatible Model','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Wireless');
object_specific = {'title':'Connectivity','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('2000');
object_specific = {'title':'Drive Capacity','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('360 Lumens');
specifics_values_array.push('LED');
specifics_values_array.push('Optic');
specifics_values_array.push('Pure Beam');
specifics_values_array.push('Ultra View');
object_specific = {'title':'Features','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('2.5" -Laptop');
object_specific = {'title':'Form Factor','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Micro SD');
specifics_values_array.push('MicroSD');
specifics_values_array.push('MicroSDHC');
specifics_values_array.push('MicroSDXC');
specifics_values_array.push('SDHC');
specifics_values_array.push('SDXC');
object_specific = {'title':'Format','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Action/Adventure');
specifics_values_array.push('Educational/Trivia');
specifics_values_array.push('Family/Kids');
specifics_values_array.push('Simulation');
specifics_values_array.push('Sports');
specifics_values_array.push('Strategy');
object_specific = {'title':'Genre','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('2 TB');
object_specific = {'title':'Hard Drive Capacity','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('USB');
object_specific = {'title':'Interface','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('External');
object_specific = {'title':'Internal/External','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('SD');
specifics_values_array.push('SDHC/SD');
object_specific = {'title':'Media Format','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('62705');
specifics_values_array.push('9V');
specifics_values_array.push('Brain Training');
specifics_values_array.push('Class 10');
specifics_values_array.push('Class 4');
specifics_values_array.push('Extreme');
specifics_values_array.push('Extreme Plus');
specifics_values_array.push('Focusing LED Light');
specifics_values_array.push('LSDMI32GBBAS633R');
specifics_values_array.push('My Horse & Me');
specifics_values_array.push('Nintendo DS');
specifics_values_array.push('Personal Yoga Training');
specifics_values_array.push('Portable');
specifics_values_array.push('Purr Pals');
specifics_values_array.push('Rechargeable');
specifics_values_array.push('S50');
specifics_values_array.push('SDHC');
specifics_values_array.push('TPU');
specifics_values_array.push('WDBMWV0020BBK');
specifics_values_array.push('WORMS OPEN WARFARE 2');
object_specific = {'title':'Model','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Bookshelf');
object_specific = {'title':'Mounting','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('32GTFc4Sanx2R4OREBS');
specifics_values_array.push('36127');
specifics_values_array.push('43961');
specifics_values_array.push('43962');
specifics_values_array.push('43963');
specifics_values_array.push('62705');
specifics_values_array.push('ART738-02CY1459PBCHE');
specifics_values_array.push('HP7');
specifics_values_array.push('LJD-S50-32GABANZ');
specifics_values_array.push('LSD64GBBANZ200');
specifics_values_array.push('LSDMI32GBBAS633R');
specifics_values_array.push('Me');
specifics_values_array.push('NDPURR');
specifics_values_array.push('NH22BP1');
specifics_values_array.push('PLT2 ');
specifics_values_array.push('PW-PB11000WHT');
specifics_values_array.push('S150');
specifics_values_array.push('SDCFXS-016G-XQ46');
specifics_values_array.push('SDSDQUA-064G-UQ46A');
specifics_values_array.push('SDSDQX-Q64G-UQ46A');
specifics_values_array.push('SDSDXS-032G');
specifics_values_array.push('TLM165');
specifics_values_array.push('TR-1422638568-PK');
specifics_values_array.push('WDBMWV0020BBK');
object_specific = {'title':'MPN','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('4x');
object_specific = {'title':'Optical Zoom','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Original');
object_specific = {'title':'Packaging','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Nintendo 3DS');
specifics_values_array.push('Nintendo DS');
object_specific = {'title':'Platform','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Laser Level');
specifics_values_array.push('Laser Measurer');
specifics_values_array.push('Stud Sensor');
object_specific = {'title':'Product Type','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('G');
object_specific = {'title':'Rating','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('80MB/s');
specifics_values_array.push('up to 48MB/s');
specifics_values_array.push('up to 80Mb/s 533x');
specifics_values_array.push('Up To 95MB/s');
object_specific = {'title':'Read Speed','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('High Definition');
object_specific = {'title':'Recording Definition','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('PAL');
specifics_values_array.push('Region Free');
object_specific = {'title':'Region Code','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('2005');
specifics_values_array.push('2006');
specifics_values_array.push('2007');
specifics_values_array.push('2008');
object_specific = {'title':'Release Year','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('All In One Speakers');
object_specific = {'title':'Speaker Type','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('16 GB');
specifics_values_array.push('32 GB');
specifics_values_array.push('32GB');
specifics_values_array.push('64 GB');
specifics_values_array.push('8 GB');
object_specific = {'title':'Storage Capacity','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Internal & Removable');
object_specific = {'title':'Storage Type','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Without Subwoofer');
object_specific = {'title':'Subwoofer','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Charging & Data Sync Cable');
specifics_values_array.push('Fitted Case/Skin');
specifics_values_array.push('Standard');
object_specific = {'title':'Type','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('015286184078');
specifics_values_array.push('039800009166');
specifics_values_array.push('4005209093279');
specifics_values_array.push('619659090203');
specifics_values_array.push('619659095987');
specifics_values_array.push('619659101633');
specifics_values_array.push('619659103682');
specifics_values_array.push('650590171316');
specifics_values_array.push('650590175161');
specifics_values_array.push('650590182275');
specifics_values_array.push('810472027807');
specifics_values_array.push('846801000753');
specifics_values_array.push('848116008950');
specifics_values_array.push('9335432019575');
object_specific = {'title':'UPC','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('60MB/s');
specifics_values_array.push('up to 48MB/s');
specifics_values_array.push('up to 80Mb/s 533x');
object_specific = {'title':'Write Speed','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
