var  welcome_text = '<p>'+
'<strong style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);">1) Can I download apps onto the TV Box?</strong><br style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);" />'+
'<span style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);">Yes, you can access Google play store and download apps as you would on your smart mobile phone. Apps can also be installed via a USB storage device or SD card.</span><br style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);" />'+
'<br style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);" />'+
'<strong style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);">2) Do I need to have a satellite receiver installed for the TV box to work?</strong><br style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);" />'+
'<span style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);">No, the TV box can be set up without a satellite receiver installed as it uses the internet to receive and send media sources such as audio and video.</span><br style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);" />'+
'<br style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);" />'+
'<strong style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);">3) Do I get HD quality from the TV Box?</strong><br style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);" />'+
'<span style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);">Yes, the TV Box is able to process and deliver true HD video to your HD TV set via an HDMI cable.</span><br style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);" />'+
'<br style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);" />'+
'<strong style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);">4) Does the TV Box have inbuilt Wifi?</strong><br style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);" />'+
'<span style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);">Yes, this is an added feature for those who can not use a data cable to connect to the Internet, signal strength for the wireless connection needs to be relatively strong for smooth streaming of HD video.</span><br style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);" />'+
'<br style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);" />'+
'<strong style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);">5) Can I watch free TV on the TV Box?</strong><br style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);" />'+
'<span style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);">Free TV is made available by a large number of sources however not all of them would be operating within legal boundaries , therefore it is the sole responsibility of the user to ensure he or she is not in violation of any of these laws. </span><br style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);" />'+
'<br style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);" />'+
'<strong style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);">6) Can I connect a keyboard and mouse to the TV Box?</strong><br style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);" />'+
'<span style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);">Yes, the TV Box supports both wired and wireless keyboards and mice. \'Check out the RC12 keyboard on our products page\'</span><br style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);" />'+
'<br style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);" />'+
'<strong style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);">7) Does the TV box support USB devices?</strong><br style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);" />'+
'<span style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);">Yes, there are 4 USB version 2.0 connection ports on the TV Box. </span><br style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);" />'+
'<br style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);" />'+
'<strong style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);">8) Can I use an SD card on the TV Box?</strong><br style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);" />'+
'<span style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);">Yes, the TV Box supports SD cards up to 32gb in capacity.</span><br style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);" />'+
'<br style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);" />'+
'<strong style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);">9) How does the TV Box connect to the Internet?</strong><br style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);" />'+
'<span style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);">The TV Box supports both wired and wireless Internet connections, wired connection is via the standard Ethernet cable \'cat 5 cable or higher via standard RJ45 connector\'</span><br style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);" />'+
'<br style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);" />'+
'<strong style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);">10) Can the TV Box be upgraded?</strong><br style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);" />'+
'<span style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);">Yes, the TV Box is updated daily with the latest films and media content automatically however modules can be added to the TV Box, these would be considered upgrades and/or packages which can be found on our packages section on the site</span><br style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);" />'+
'<br style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);" />'+
'<strong style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);">11) Why are some Films and TV stations there but not working?</strong><br style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);" />'+
'<span style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);">Even though we try our best to avoid these situations, the TV Box relies on feeds which come from the internet, this means the TV Box needs to connect to other machines on the internet to work, when these machines are not transmitting a signal, the TV Box will consider this to be ab dead link. In this case please find an alternative link for the same media.</span><br style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);" />'+
'<br style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);" />'+
'<strong style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);">12) Can I use the TV Box for video calling?</strong><br style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);" />'+
'<span style="color: rgb(58, 58, 58); font-family: \'Open Sans\', sans-serif; font-size: 14px; line-height: 24px; background-color: rgb(225, 225, 225);">Yes, the TV Box supports video calls, simply connect a camera to one of the 4 USB slots available, install any necessary drivers and you can connect to your loved ones or business partners via Skype or any similar supported application.</span></p>';
