var specifics_array = new Array();
specifics_values_array = new Array();
specifics_values_array.push('PiPo');
specifics_values_array.push('Urban Armor Gear');
object_specific = {'title':'Brand','custom_title':'Beats','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Black');
object_specific = {'title':'Colour','custom_title':'White','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('For Apple');
specifics_values_array.push('For Samsung');
specifics_values_array.push('Samsung');
object_specific = {'title':'Compatible Brand','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('For iPod Classic');
specifics_values_array.push('For iPod Mini');
specifics_values_array.push('For iPod Nano');
specifics_values_array.push('For iPod Shuffle');
specifics_values_array.push('For iPod Touch');
specifics_values_array.push('iPhone 5/5S');
specifics_values_array.push('Samsung Galaxy S5');
object_specific = {'title':'Compatible Model','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Without Contract');
object_specific = {'title':'Contract','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('3 months');
object_specific = {'title':'Manufacturer warranty','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Composite');
specifics_values_array.push('Plastic');
object_specific = {'title':'Material','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('UAG-IPH5-WHT/BLK-W/SCRN-VP');
object_specific = {'title':'MPN','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Android 4.2,2');
object_specific = {'title':'Operating System','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Max M9 Pro ');
object_specific = {'title':'Product Line','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('1920 x 1200 pixels');
object_specific = {'title':'Resolution','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('10.1"');
object_specific = {'title':'Screen Size','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('32GB');
object_specific = {'title':'Storage Capacity','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Fitted Cases/Skins');
specifics_values_array.push('Tablet');
object_specific = {'title':'Type','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
