var specifics_array = new Array();
specifics_values_array = new Array();
specifics_values_array.push('Ear');
specifics_values_array.push('Navel');
specifics_values_array.push('Nose');
specifics_values_array.push('Tongue');
specifics_values_array.push('Universal');
object_specific = {'title':'Body Area','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Body Jewelry');
specifics_values_array.push('DC COMICS');
specifics_values_array.push('Hasbro');
specifics_values_array.push('marvel');
specifics_values_array.push('party rock');
specifics_values_array.push('Spiderman');
specifics_values_array.push('The Hundreds');
specifics_values_array.push('Wild Tribe ');
object_specific = {'title':'Brand','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Blue');
object_specific = {'title':'Color','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Chile');
object_specific = {'title':'Country/Region of Manufacture','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Helix');
specifics_values_array.push('Industrial');
specifics_values_array.push('Lobe');
object_specific = {'title':'Ear Area','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('la-pousette-posts-and-clutches');
object_specific = {'title':'Fastening','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('00g (10 mm)');
specifics_values_array.push('1/2 inch (12.7mm)');
specifics_values_array.push('10g (2.4 mm)');
specifics_values_array.push('14g (1.6 mm)');
specifics_values_array.push('7/16 inch (11mm)');
object_specific = {'title':'Gauge (Thickness)','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('7/16'' (11mm)');
object_specific = {'title':'Length','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Black');
specifics_values_array.push('Brown');
specifics_values_array.push('Chrome');
specifics_values_array.push('Clear');
specifics_values_array.push('Green');
specifics_values_array.push('Multi-Color');
specifics_values_array.push('Pink');
specifics_values_array.push('Silver');
specifics_values_array.push('White');
object_specific = {'title':'Main Color','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('No Stone');
object_specific = {'title':'Main Stone','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Acrylic');
specifics_values_array.push('Brass');
specifics_values_array.push('Enamel');
specifics_values_array.push('Feather');
specifics_values_array.push('Leather');
specifics_values_array.push('Rubber');
specifics_values_array.push('Stainless Steel');
specifics_values_array.push('Stone');
object_specific = {'title':'Material','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Brass');
specifics_values_array.push('No Metal');
specifics_values_array.push('Stainless Steel');
specifics_values_array.push('Stainless-steel');
specifics_values_array.push('Surgical Steel');
specifics_values_array.push('Titanium Plated');
object_specific = {'title':'Metal','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('316L');
object_specific = {'title':'Metal Purity','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('One Size');
object_specific = {'title':'Size','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Chain');
specifics_values_array.push('Pendant');
specifics_values_array.push('Snapback');
specifics_values_array.push('Stud');
specifics_values_array.push('stud-earrings');
specifics_values_array.push('Wristband');
object_specific = {'title':'Style','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Signs & Symbols');
object_specific = {'title':'Theme','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Bars & Barbells');
specifics_values_array.push('Cartilage');
specifics_values_array.push('Curved Bars');
specifics_values_array.push('earring');
specifics_values_array.push('Industrials & Scaffolds');
specifics_values_array.push('Studs');
specifics_values_array.push('Tapers & Stretchers');
specifics_values_array.push('Tunnels & Plugs');
object_specific = {'title':'Type','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
