var specifics_array = new Array();
specifics_values_array = new Array();
specifics_values_array.push('2xtremz');
specifics_values_array.push('ALFANI');
specifics_values_array.push('ALLSORTS');
specifics_values_array.push('ASOS');
specifics_values_array.push('ATMOSPHERE');
specifics_values_array.push('AVOCADO');
specifics_values_array.push('BANNONG');
specifics_values_array.push('Barkins');
specifics_values_array.push('BLUEJADE');
specifics_values_array.push('BOOHOO');
specifics_values_array.push('CAROLINE MORGAN');
specifics_values_array.push('CHAIN REACTION');
specifics_values_array.push('CI.PAES');
specifics_values_array.push('CITY CHIC');
specifics_values_array.push('CLASSIC');
specifics_values_array.push('Cocolatte');
specifics_values_array.push('Cotton On');
specifics_values_array.push('Country Road');
specifics_values_array.push('CROSSROADS');
specifics_values_array.push('Cue In The City');
specifics_values_array.push('DANIELA');
specifics_values_array.push('EDITED');
specifics_values_array.push('ELEGANT');
specifics_values_array.push('EMERSON');
specifics_values_array.push('ERMIS WORLD');
specifics_values_array.push('EVE');
specifics_values_array.push('Events Collection');
specifics_values_array.push('EXPRESSION');
specifics_values_array.push('EXPRESSIONS');
specifics_values_array.push('FACE OFF');
specifics_values_array.push('FACEOFF');
specifics_values_array.push('Filo');
specifics_values_array.push('FLETCHERJONES');
specifics_values_array.push('FLOWER');
specifics_values_array.push('FOREVERNEW');
specifics_values_array.push('FREE FUSION');
specifics_values_array.push('FrontPage');
specifics_values_array.push('G.');
specifics_values_array.push('Geoff Bade');
specifics_values_array.push('GeoffBade');
specifics_values_array.push('GIANNI RODINI');
specifics_values_array.push('GIRL EXPRESS');
specifics_values_array.push('GLAMA ZON');
specifics_values_array.push('GLASSONS');
specifics_values_array.push('Guess');
specifics_values_array.push('HD');
specifics_values_array.push('HOT OPTIONS');
specifics_values_array.push('I.D.S');
specifics_values_array.push('IMPULSE');
specifics_values_array.push('iNSPYR');
specifics_values_array.push('INTANGIBLE');
specifics_values_array.push('JACQUI-E');
specifics_values_array.push('JAG');
specifics_values_array.push('Jaqueine Femme');
specifics_values_array.push('Jaqui-E');
specifics_values_array.push('JERSEYGIRL');
specifics_values_array.push('Just Jeans');
specifics_values_array.push('K.Y. FASHION');
specifics_values_array.push('KJD');
specifics_values_array.push('LAURA K');
specifics_values_array.push('LeChateau');
specifics_values_array.push('LILI');
specifics_values_array.push('LIZ JORDAN');
specifics_values_array.push('LUSHOUS');
specifics_values_array.push('Mansour');
specifics_values_array.push('Marco Polo');
specifics_values_array.push('Master&Margarita');
specifics_values_array.push('Millers');
specifics_values_array.push('MIX');
specifics_values_array.push('MIX IT');
specifics_values_array.push('MOOLOOLA');
specifics_values_array.push('MORRISSEY');
specifics_values_array.push('NET GIRL');
specifics_values_array.push('NEW YORK INTIMATES');
specifics_values_array.push('NewLook');
specifics_values_array.push('Now');
specifics_values_array.push('OPCAO');
specifics_values_array.push('Osop');
specifics_values_array.push('PAPER SCISSORS');
specifics_values_array.push('Peter Morrissey');
specifics_values_array.push('PIPER');
specifics_values_array.push('PORTMANS');
specifics_values_array.push('PRILIS');
specifics_values_array.push('REGATTA');
specifics_values_array.push('RENZE VORSA');
specifics_values_array.push('Review');
specifics_values_array.push('ROCKMAMA');
specifics_values_array.push('ROCKMANS');
specifics_values_array.push('SALLY');
specifics_values_array.push('Savannah');
specifics_values_array.push('SCS');
specifics_values_array.push('SEDUCE');
specifics_values_array.push('SES');
specifics_values_array.push('SHEIKE');
specifics_values_array.push('SHOW PONY');
specifics_values_array.push('SILHOUETTE');
specifics_values_array.push('SIROCCO');
specifics_values_array.push('SOLUTIONS');
specifics_values_array.push('SPOIL YOURSELF');
specifics_values_array.push('Sports Girl');
specifics_values_array.push('Stitches');
specifics_values_array.push('SUITE 62');
specifics_values_array.push('Sundus');
specifics_values_array.push('SUNNY GIRL');
specifics_values_array.push('SUPRE');
specifics_values_array.push('Suzannegrae');
specifics_values_array.push('Target');
specifics_values_array.push('TATTOO');
specifics_values_array.push('TEMT');
specifics_values_array.push('TOGETHER');
specifics_values_array.push('TOKITO');
specifics_values_array.push('TOP GIRL');
specifics_values_array.push('TS');
specifics_values_array.push('undercoverWear');
specifics_values_array.push('UNERCOVER WEAR');
specifics_values_array.push('URBAN');
specifics_values_array.push('Valley Girl');
specifics_values_array.push('VALLEYGIRL');
specifics_values_array.push('Yarratrail');
specifics_values_array.push('YPV');
object_specific = {'title':'Brand','custom_title':'All Brands','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Career');
specifics_values_array.push('Casual');
specifics_values_array.push('Cocktail');
specifics_values_array.push('Evening, Occasion');
specifics_values_array.push('Summer/Beach');
object_specific = {'title':'Occasion','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('10');
specifics_values_array.push('12');
specifics_values_array.push('14');
specifics_values_array.push('16');
specifics_values_array.push('18');
specifics_values_array.push('2');
specifics_values_array.push('20');
specifics_values_array.push('24');
specifics_values_array.push('40');
specifics_values_array.push('6');
specifics_values_array.push('8');
specifics_values_array.push('L');
specifics_values_array.push('M');
specifics_values_array.push('Plus Size');
specifics_values_array.push('S');
specifics_values_array.push('XL');
specifics_values_array.push('XS');
specifics_values_array.push('XXL');
specifics_values_array.push('XXS');
object_specific = {'title':'Size','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
