var specifics_array = new Array();
specifics_values_array = new Array();
specifics_values_array.push('Blue');
specifics_values_array.push('Green');
specifics_values_array.push('Grey');
specifics_values_array.push('Multi');
specifics_values_array.push('Orange');
specifics_values_array.push('Pink');
specifics_values_array.push('Purple');
specifics_values_array.push('Red');
object_specific = {'title':'Main Colour','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('All Occasions');
specifics_values_array.push('Baby Shower');
specifics_values_array.push('Birthday, Child');
specifics_values_array.push('Moving House');
object_specific = {'title':'Occasion','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Animals');
specifics_values_array.push('Camping');
specifics_values_array.push('Clown');
specifics_values_array.push('Dance');
specifics_values_array.push('Fairy Tales');
specifics_values_array.push('Flowers');
specifics_values_array.push('Food/Kitchen');
specifics_values_array.push('Hearts');
specifics_values_array.push('Knights & Medieval');
specifics_values_array.push('Music');
specifics_values_array.push('Party');
specifics_values_array.push('Pirates');
specifics_values_array.push('Princess/Fairies');
specifics_values_array.push('Robots');
specifics_values_array.push('Rocket Ships & Space');
specifics_values_array.push('Sleepover');
specifics_values_array.push('Sport');
specifics_values_array.push('Superhero');
specifics_values_array.push('TV & Celebrities');
specifics_values_array.push('Vehicles');
object_specific = {'title':'Theme','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Birthday');
specifics_values_array.push('Invitation');
specifics_values_array.push('Moving House');
specifics_values_array.push('Thank You Card');
object_specific = {'title':'Type','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
