    <script type="text/javascript">
    <!--
        var LANG = {
          'is_valid_email' : '<?php echo $this->lang->line('is_valid_email'); ?>',
          'fill_out_username': '<?php echo $this->lang->line('fill_out_username'); ?>',
          'fill_out_password' : '<?php echo $this->lang->line('fill_out_password'); ?>',
          'checking_validity' : '<?php echo $this->lang->line('checking_validity'); ?>',
          'checking_availability' : '<?php echo $this->lang->line('checking_availability'); ?>',
          'email_is_valid' : '<?php echo $this->lang->line('email_is_valid'); ?>',
          'email_is_taken' : '<?php echo $this->lang->line('email_is_taken'); ?>',
          'email_is_available' : '<?php echo $this->lang->line('email_is_available'); ?>',
          'email_characters' : '<?php echo $this->lang->line('email_characters'); ?>',
          'username_is_valid' : '<?php echo $this->lang->line('username_is_valid'); ?>',
          'username_available' : '<?php echo $this->lang->line('username_available'); ?>',
          'username_exists' : '<?php echo $this->lang->line('username_exists'); ?>',
          'username_minlength' : '<?php echo $this->lang->line('username_minlength'); ?>',
          'username_maxlength' : '<?php echo $this->lang->line('username_maxlength'); ?>',
          'is_valid_username' : '<?php echo $this->lang->line('is_valid_username'); ?>',
          'fill_out_first_name' : '<?php echo $this->lang->line('fill_out_first_name'); ?>',
          'first_name_minlength' : '<?php echo $this->lang->line('first_name_minlength'); ?>',
          'first_name_maxlength' : '<?php echo $this->lang->line('first_name_maxlength'); ?>',
          'fill_out_last_name' : '<?php echo $this->lang->line('fill_out_last_name'); ?>',
          'last_name_minlength' : '<?php echo $this->lang->line('last_name_minlength'); ?>',
          'last_name_maxlength' : '<?php echo $this->lang->line('last_name_maxlength'); ?>',
          'fill_out_email' : '<?php echo $this->lang->line('fill_out_email'); ?>',
          'email_maxlength' : '<?php echo $this->lang->line('email_maxlength'); ?>',
          'password_minlength' : '<?php echo $this->lang->line('password_minlength'); ?>',
          'password_maxlength' : '<?php echo $this->lang->line('password_maxlength'); ?>',
          'password_match' : '<?php echo $this->lang->line('password_match'); ?>',
          'password_profile' : '<?php echo $this->lang->line('password_profile'); ?>',
          'password_current' : '<?php echo $this->lang->line('password_current'); ?>',
          'password_new' : '<?php echo $this->lang->line('password_new'); ?>',
          'password_new_max' : '<?php echo $this->lang->line('password_new_max'); ?>',
          'password_repeat' : '<?php echo $this->lang->line('password_repeat'); ?>',
          'password_no_match' : '<?php echo $this->lang->line('password_no_match'); ?>',
          'search_data' : '<?php echo $this->lang->line('search_data'); ?>',
          'email_empty' : '<?php echo $this->lang->line('email_empty'); ?>',
          'recaptcha_required' : '<?php echo $this->lang->line('recaptcha_required'); ?>'
        };
    -->
    </script>
