document.write('<ul class=\'nav navbar-nav\'>');
document.write('<li class="menu-item"><a href="http://stores.ebay.co.uk/BearingShopUK/bearings-/_i.html?_fsub=4580653011">Bearings</a>');
document.write('<ul class=\'nav navbar-nav\'>');
document.write('<li class="menu-item"><a href="http://stores.ebay.co.uk/BearingShopUK/ball-bearings-(10-55mm-bore)-/_i.html?_fsub=4580655011">Bearings 10-55mm Bore</a></li>');
document.write('<li class="menu-item"><a href="http://stores.ebay.co.uk/BearingShopUK/ball-bearings-(%3E60mm-bore)-/_i.html?_fsub=5100936011">Ball Bearings >60mm Bore</a></li>');
document.write('<li class="menu-item"><a href="http://stores.ebay.co.uk/BearingShopUK/skf-high-temp-bearings-/_i.html?_fsub=5100935011">High Temperature Ball Bearings</a></li>');
document.write('<li class="menu-item"><a href="http://stores.ebay.co.uk/BearingShopUK/thin-section-/_i.html?_fsub=4587828011">Thin Section Ball Bearings</a></li>');
document.write('<li class="menu-item"><a href="http://stores.ebay.co.uk/BearingShopUK/skf-metric-tapers-/_i.html?_fsub=5100934011">Metric Taper Bearings</a></li>');
document.write('<li class="menu-item"><a href="http://stores.ebay.co.uk/BearingShopUK/rod-ends-/_i.html?_fsub=4587827011">Rod End Bearings</a></li>');
document.write('</ul>');
document.write('</li>');
document.write('<li class="menu-item"><a href="http://stores.ebay.co.uk/BearingShopUK/belts-/_i.html?_fsub=4580654011">Belts</a>');
document.write('<ul class=\'nav navbar-nav\'>');
document.write('<li class="menu-item"><a href="http://stores.ebay.co.uk/BearingShopUK/v-belts-/_i.html?_fsub=4580747011">V Belts</a>');
document.write('<ul class=\'nav navbar-nav\'>');
document.write('<li class="menu-item"><a href="http://stores.ebay.co.uk/BearingShopUK/Z-section-/_i.html?_fsub=5497262011&_sid=126180801&_trksid=p4634.c0.m322">Z Section</a></li>');
document.write('<li class="menu-item"><a href="http://stores.ebay.co.uk/BearingShopUK/A-section-/_i.html?_fsub=5497263011&_sid=126180801&_trksid=p4634.c0.m322">A Section</a></li>');
document.write('<li class="menu-item"><a href="http://stores.ebay.co.uk/BearingShopUK/B-section-/_i.html?_fsub=5497264011&_sid=126180801&_trksid=p4634.c0.m322">B Section</a></li>');
document.write('<li class="menu-item"><a href="http://stores.ebay.co.uk/BearingShopUK/C-section-/_i.html?_fsub=5497265011&_sid=126180801&_trksid=p4634.c0.m322">C Section</a></li>');
document.write('<li class="menu-item"><a href="http://stores.ebay.co.uk/BearingShopUK/D-section-/_i.html?_fsub=5497266011&_sid=126180801&_trksid=p4634.c0.m322">D Section</a></li>');
document.write('</ul>');
document.write('</li>');
document.write('<li class="menu-item"><a href="http://stores.ebay.co.uk/BearingShopUK/wedge-belts-/_i.html?_fsub=4580793011">Wedge Belts</a></li>');
document.write('<li class="menu-item"><a href="http://stores.ebay.co.uk/BearingShopUK/kevlar-belts-/_i.html?_fsub=4580833011">Kevlar Belts</a>');
document.write('<ul class=\'nav navbar-nav\'>');
document.write('<li class="menu-item"><a href="http://stores.ebay.co.uk/BearingShopUK/3l-section-/_i.html?_fsub=4583773011">3L Section</a></li>');
document.write('<li class="menu-item"><a href="http://stores.ebay.co.uk/BearingShopUK/4l-section-/_i.html?_fsub=4583774011">4L Section</a></li>');
document.write('<li class="menu-item"><a href="http://stores.ebay.co.uk/BearingShopUK/5l-section-/_i.html?_fsub=4583775011">5L Section</a></li>');
document.write('</ul>');
document.write('</li>');
document.write('<li class="menu-item"><a href="http://stores.ebay.co.uk/BearingShopUK/mower-belts-/_i.html?_fsub=4580834011">Mower Belts</a></li>');
document.write('<li class="menu-item"><a href="http://stores.ebay.co.uk/BearingShopUK/automotive-fan-belts-/_i.html?_fsub=4580891011">Automotive Belts</a></li>');
document.write('<li class="menu-item"><a href="http://stores.ebay.co.uk/BearingShopUK/gates-polyflex-/_i.html?_fsub=4580890011">Gates Polyflex</a></li>');
document.write('<li class="menu-item"><a href="http://stores.ebay.co.uk/BearingShopUK/nutlink-/_i.html?_fsub=4587838011">Nutlink Belting</a></li>');
document.write('</ul>');
document.write('</li>');
document.write('<li class="menu-item"><a href="">Pulleys & Bushes</a>');
document.write('<ul class=\'nav navbar-nav\'>');
document.write('<li class="menu-item"><a href="http://stores.ebay.co.uk/BearingShopUK/v-belt-pulleys-/_i.html?_fsub=4587867011">V Pulleys</a></li>');
document.write('<li class="menu-item"><a href="http://stores.ebay.co.uk/BearingShopUK/taperlock-bushes-/_i.html?_fsub=4587840011">Taperlock Bushes</a></li>');
document.write('</ul>');
document.write('</li>');
document.write('<li class="menu-item"><a href="">Seals & Clips</a>');
document.write('<ul class=\'nav navbar-nav\'>');
document.write('<li class="menu-item"><a href="http://stores.ebay.co.uk/BearingShopUK/Oilseals-/_i.html?_fsub=5100941011&_sid=126180801&_trksid=p4634.c0.m322">Oilseals</a></li>');
document.write('<li class="menu-item"><a href="http://stores.ebay.co.uk/BearingShopUK/ORings-/_i.html?_fsub=5498381011&_sid=126180801&_trksid=p4634.c0.m322">O\'Rings</a>');
document.write('<ul class=\'nav navbar-nav\'>');
document.write('<li class="menu-item"><a href="http://stores.ebay.co.uk/BearingShopUK/Packs-of-10-/_i.html?_fsub=5498397011&_sid=126180801&_trksid=p4634.c0.m322">Pack of 10</a></li>');
document.write('<li class="menu-item"><a href="http://stores.ebay.co.uk/BearingShopUK/Packs-of-50-/_i.html?_fsub=5498398011&_sid=126180801&_trksid=p4634.c0.m322">Pack of 50</a></li>');
document.write('<li class="menu-item"><a href="http://stores.ebay.co.uk/BearingShopUK/Packs-of-100-/_i.html?_fsub=5498399011&_sid=126180801&_trksid=p4634.c0.m322">Pack of 100</a></li>');
document.write('<li class="menu-item"><a href="http://stores.ebay.co.uk/BearingShopUK/fluid-power-/_i.html?_fsub=7860732011">Fluid Power</a></li>');
document.write('</ul>');
document.write('</li>');
document.write('</ul>');
document.write('</li>');
document.write('</ul>');
