document.write('<div class="row footer-custom-background footer-container">');
document.write('<div class="container">');
document.write('<!--green-->');
document.write('<div class="rockscripts-footer-top-bar">');
document.write('<div class="rockscripts-left"><b>       Hotline: 0355 / 52950100</b> - Montag-Freitag: 9.00 - 16.00 Uhr - Samstag: 9.00 - 12.00 Uhr');
document.write('</div>');
document.write('<div class="rockscripts-right rockscripts-footer-right-title"> Impressum');
document.write('<p class="caret"></p>');
document.write('</div>');
document.write('</div>');
document.write('<!--green-->');
document.write('<div class="rockscripts-footer-elements">');
document.write('<div class="rockscripts-logo-footer rockscripts-left"> <img title="Handelsagentur-OST" class="logo1" src="http://dev.licht.farm/ebay/hago/template/img/logo.jpg"> </div>');
document.write('<div class="rockscripts-links-footer rockscripts-left">');
document.write('<div class="block">');
document.write('<div class="block-wrap">');
document.write('<div class="block_content">');
document.write('<ul class="widget-items">');
document.write('<li class="widget-module">');
document.write('<div class="block myaccount">');
document.write('<p class="title_block">Informationen</p>');
document.write('<div class="block_content">');
document.write('<ul class="bullet">');
document.write('<li><a href="http://members.ebay.de/ws/eBayISAPI.dll?ViewUserPage&userid=trade.99#Bewertung" rel="nofollow" title="Bewertung">Bewertung</a> </li>');
document.write('<li><a href="http://members.ebay.de/ws/eBayISAPI.dll?ViewUserPage&userid=trade.99#Impressum" rel="nofollow" title="Impressum">Impressum</a> </li>');
document.write('<li><a href="http://members.ebay.de/ws/eBayISAPI.dll?ViewUserPage&userid=trade.99#AGB" rel="nofollow" title="Die AGBÂ´s">Die AGBs</a> </li>');
document.write('<li><a href="http://members.ebay.de/ws/eBayISAPI.dll?ViewUserPage&userid=trade.99#BatterieEntsorgung" rel="nofollow" title="InfoÂ´s zur Batterieentsorgung.">Infos zur Lieferzeit</a> </li>');
document.write('</ul>');
document.write('</div>');
document.write('</div>');
document.write('</li>');
document.write('</ul>');
document.write('</div>');
document.write('</div>');
document.write('</div>');
document.write('<!--BLOCK-->');
document.write('<div style="margin-left: -2px;" class="block ">');
document.write('<div class="block-wrap">');
document.write('<div class="block_content">');
document.write('<ul class="widget-items">');
document.write('<li class="widget-module">');
document.write('<div class="block myaccount">');
document.write('<p class="title_block"> </p>');
document.write('<div class="block_content">');
document.write('<ul class="bullet">');
document.write('<li><a href="http://members.ebay.de/ws/eBayISAPI.dll?ViewUserPage&userid=trade.99#VorDemBieten" rel="nofollow" title="InfoÂ´s vor dem Bieten">Infos vor dem Bieten</a> </li>');
document.write('<li><a href="http://members.ebay.de/ws/eBayISAPI.dll?ViewUserPage&userid=trade.99#NachAuktion" rel="nofollow" title="Nach erfolgreicher Auktion">Nach erfolgreicher Auktion</a> </li>');
document.write('<li><a href="http://members.ebay.de/ws/eBayISAPI.dll?ViewUserPage&userid=trade.99#Versand" rel="nofollow" title="Versand und Verpackung">Versand und Verpackung</a> </li>');
document.write('<li><a href="http://members.ebay.de/ws/eBayISAPI.dll?ViewUserPage&userid=trade.99#BatterieEntsorgung" rel="nofollow" title="InfoÂ´s zur Lieferzeit.">Infos zur Batterieentsorgung</a> </li>');
document.write('</ul>');
document.write('</div>');
document.write('</div>');
document.write('</li>');
document.write('</ul>');
document.write('</div>');
document.write('</div>');
document.write('</div>');
document.write('<!--BLOCK-->');
document.write('<div class="block">');
document.write('<div class="block-wrap">');
document.write('<div class="block_content">');
document.write('<ul class="widget-items">');
document.write('<li class="widget-module">');
document.write('<div class="block_various_links" id="block_various_links_footer">');
document.write('<p class="title_block"> </p>');
document.write('<ul>');
document.write('<li class="item"><a href="http://members.ebay.de/ws/eBayISAPI.dll?ViewUserPage&userid=trade.99#Widerrufsrecht" title="Widerrufsrecht">Widerrufsrecht</a> </li>');
document.write('<li class="item"><a href="http://members.ebay.de/ws/eBayISAPI.dll?ViewUserPage&userid=trade.99#b10" title="DatenschutzerklÃ¤rung">Datenschutzerklärung</a> </li>');
document.write('<li class="item"><a href="http://members.ebay.de/ws/eBayISAPI.dll?ViewUserPage&userid=trade.99" title="Ebay-Mich">Ebay-Mich</a> </li>');
document.write('<li class="item"><a href="http://stores.ebay.de/99spaces" title="Ebay-Shop">Ebay-Shop</a> </li>');
document.write('</ul>');
document.write('</div>');
document.write('</li>');
document.write('</ul>');
document.write('</div>');
document.write('</div>');
document.write('</div>');
document.write('</div>');
document.write('<div class="right-footer-widget">');
document.write('<div class="rockscripts-return-widget"> Handelsagentur-OST, Daniel Nevoigt<br>');
document.write('<br>');
document.write('Gerhart-Hauptmann-Str. 15<br>');
document.write('Rampe 2a<br>');
document.write('03044 Cottbus');
document.write('<ul>');
document.write('<li><em class="icon-phone"></em>Tel: +49 (0) 355-52950100 </li>');
document.write('<li style="padding-left:20px;">Fax: +49 (0) 355-52950101</li>');
document.write('<li><em class="icon-email"></em><a>info@handelsagentur-ost.de</a> </li>');
document.write('</ul>');
document.write('</div>');
document.write('</div>');
document.write('</div>');
document.write('<div class="pull-right hidden-xs" id="es_footer">');
document.write('<div class="visible-lg visible-md visible-sm" id="es_formFooter">');
document.write('<form method="get" action="" class="store-home-url" name="search" id="es_searchform">');
document.write('<fieldset class="es_search">');
document.write('<input type="text" onfocus="if(this.value ==\'Search Our Ebay Store...\' ) this.value=\'\'" onblur="if(this.value==\'\') this.value=\'Search Our Ebay Store...\'" value="Search Our Ebay Store..." class="es_box" name="_nkw">');
document.write('<button title="Submit Search" class="es_btn" onclick="search()"><div class="button-search"></div></button>');
document.write('</fieldset>');
document.write('</form>');
document.write('</div>');
document.write('<div class="pull-right visible-lg visible-md visible-sm" id="es_formLinks">');
document.write('');
document.write('<script class="script" type="text/javascript" async>');
document.write('include1("footer_menu.js");');
document.write('</script>');
document.write('<ul class="footer-menu-content">');
document.write('</ul>');
document.write('</div>');
document.write('<div class="copyright"></div>');
document.write('</div>');
document.write('<div style="margin-bottom :5px; margin-top: 0px;margin-right: 25px;" class="pull-right hide">');
document.write('<div class="social-media-buttons">');
document.write('<script class="script" type="text/javascript" sync>');
document.write('include("social_media_buttons_parts.js");');
document.write('</script>');
document.write('</div>');
document.write('</div>');
document.write('</div>');
document.write('</div>');
document.write('<div class="powered-by">');
document.write('<a target="_blank" href="http://rockscripts.org" class="powered_link1">Powered by: <img class="rockscripts-logo-small" src="http://dev.licht.farm/ebay/hago/template/img/rockscripts-small.png"></a>');
document.write('</div>');
