document.write('<!--[if IE 9 ]>');
document.write('<style>');
document.write('</style>');
document.write('<![endif]-->');
document.write('<div class="row">');
document.write('<div class="col-sm-2">');
document.write('</div>');
document.write('<div class="col-sm-10" style="padding-right: 0px;" >');
document.write('<div id="es_topLinksContainer">');
document.write('<div class="line-decorative"></div>');
document.write('</div>');
document.write('</div>');
document.write('</div>');
document.write('<div class="row">');
document.write('<div class="col-sm-12" id="es_header">');
document.write('<div class="rows-header-container">');
document.write('<div class="row-header">');
document.write('<div class="top-banner-services">');
document.write('<img src="http://dev.licht.farm/ebay/hago/template/img/delivery-on-time-best-services.png"/>');
document.write('</div>');
document.write('</div>');
document.write('<div class="row-header">');
document.write('<div class="top-header-links">');
document.write('<div class="rockscripts-links-information"> <a title="Ebay-Shop" href="http://stores.ebay.de/99spaces" target="_blank">Ebay-Shop <img style="width:14px;" src="http://dev.licht.farm/ebay/hago/template/img/iconStoresNW_20x20.gif"></a>  |   <a title="Ebay-Mich" href="http://members.ebay.de/ws/eBayISAPI.dll?ViewUserPage&userid=trade.99">Ebay-Mich <img src="http://dev.licht.farm/ebay/hago/template/img/aboutme-small.gif"></a>  |   <a title="DatenschutzerklÃ¤rung" href="http://members.ebay.de/ws/eBayISAPI.dll?ViewUserPage&userid=trade.99#b10">Datenschutzerklärung</a>  |   <a title="Widerrufsrecht" href="http://members.ebay.de/ws/eBayISAPI.dll?ViewUserPage&userid=trade.99#Widerrufsrecht">Widerrufsrecht</a>  |   <a title="Widerrufsrecht" href="http://members.ebay.de/ws/eBayISAPI.dll?ViewUserPage&userid=trade.99#Impressum">Impressum</a>');
document.write('</div>');
document.write('</div>');
document.write('<div class="top-header-search-form">');
document.write('<div class="header-search-box visible-md visible-lg visible-sm">');
document.write('<form class="navbar-form store-home-url" role="search" target="_top" method="get" action="">');
document.write('<div class="input-group">');
document.write('<input type="text" id="nkw" name="_nkw"  class="form-control" placeholder="">');
document.write('<span class="input-group-btn">');
document.write('<input class="btn btn-default submit_search button-search search-icon-on-input" type="submit" value="">');
document.write('</span>');
document.write('</div>');
document.write('</form>');
document.write('</div>');
document.write('</div>');
document.write('</div>');
document.write('<div class="row-header">');
document.write('<div style="word-spacing:0.5em;" class="rockscripts-categories-links"> <span style="font-size:14px;"><b>Hotline: 0355 / 52950100</b></span> - Montag-Freitag: 9.00 - 16.00 Uhr - Samstag: 9.00 - 12.00 Uhr </div>');
document.write('</div>');
document.write('</div>');
document.write('<span id="logo-content-IE9">');
document.write('</span>');
document.write('<script type="text/javascript">');
document.write('include1("logo.js");');
document.write('</script>');
document.write('<script type="text/javascript">');
document.write('include1("header_background.js");');
document.write('</script>');
document.write('</div>');
document.write('</div>');
