var pages_array = new Array();
object = {'title':'About Us','url':'http://stores.ebay.com.au/Alchemy-Suiting/About-Us.html','content':'<div>	<span style="font-size:16px;">Our mission is to make Australian men feel golden. We want them to feel confident and to stand out from their peers.</span></div><div>	<span style="font-size:16px;">We want you to be able to get all the benefits of custom suits whilst paying less than off the rack.</span></div><div></div><div>	<span style="font-size:16px;">Our motto is "Whatever you can dream of, we can create".</span></div><div></div><div></div><div>	<span style="font-size:20px;"><strong>QUALITY</strong></span></div><div></div><div>	<span style="font-size:16px;">Quality is our utmost priority, and we don’t believe in that you have to pay outlandish prices for it either. We traveled the world searching for the luxury fabrics, tasteful designs and expert craftsmanship. Everything gets the attention to detail only 100% handmade can offer.</span></div><div></div><div>	<span style="font-size:16px;">Quality is our obsession and you’ll experience it first hand the moment you put on an Alchemy Suiting garment.</span></div><div></div><div>	<span style="font-size:20px;"><strong>SERVICE</strong></span></div><div></div><div>	<span style="font-size:16px;">And of course, all that quality wouldn’t be worth a cent unless it fits you just right. We not only guarantee that fit, we promise to hold your hand every step of the way there. We’ll always steer you true and our stylists are simply experts when it comes to helping you achieve not only a flawless fit, but also a fashionable look.</span></div><div></div>'};
pages_array.push(object);
object = {'title':'Shipping','url':'http://stores.ebay.com.au/Alchemy-Suiting/Shipping.html','content':'<p>	Your Shipping Information here!</p>'};
pages_array.push(object);
object = {'title':'Returns','url':'http://stores.ebay.com.au/Alchemy-Suiting/Returns.html','content':'<p>	Your Returns content here!</p>'};
pages_array.push(object);
object = {'title':'Feedbacks','url':'http://stores.ebay.com.au/Alchemy-Suiting/Feedbacks.html','content':'<p>	Your Feedbacks Information here!</p>'};
pages_array.push(object);
