var specifics_array = new Array();
specifics_values_array = new Array();
specifics_values_array.push('"Handmade"');
specifics_values_array.push('American Eagle');
specifics_values_array.push('American Eagle Outfitters');
specifics_values_array.push('Cellet');
specifics_values_array.push('Charlotte Russe');
specifics_values_array.push('Cherokee');
specifics_values_array.push('Color Story');
specifics_values_array.push('COOGI');
specifics_values_array.push('Elizabeth Taylor');
specifics_values_array.push('FOREVER 21');
specifics_values_array.push('GlobalTV');
specifics_values_array.push('MAC');
specifics_values_array.push('Mary Kay');
specifics_values_array.push('Maybelline');
specifics_values_array.push('Motorola');
specifics_values_array.push('MYBAT');
specifics_values_array.push('Nintendo');
specifics_values_array.push('Physicians Formula');
specifics_values_array.push('Shiseido');
specifics_values_array.push('Sparkling White Diamonds');
specifics_values_array.push('Unbranded');
specifics_values_array.push('Visual Land');
object_specific = {'title':'Brand','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Arctic White');
specifics_values_array.push('Black');
specifics_values_array.push('Clear');
specifics_values_array.push('Hot Pink/Black');
specifics_values_array.push('Mix Black');
specifics_values_array.push('Multi-Color');
specifics_values_array.push('Pink');
specifics_values_array.push('Purple');
specifics_values_array.push('Royal Purple');
specifics_values_array.push('White');
object_specific = {'title':'Color','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('For HTC');
specifics_values_array.push('HTC');
specifics_values_array.push('Motorola');
specifics_values_array.push('Universal');
object_specific = {'title':'Compatible Brand','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('ADR6330 (Rhyme)');
specifics_values_array.push('Citrus WX445');
object_specific = {'title':'Compatible Model','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Kindle 2');
specifics_values_array.push('Kindle Fire');
specifics_values_array.push('Kindle Fire HD');
specifics_values_array.push('Nexus 7');
specifics_values_array.push('Nook');
specifics_values_array.push('Prestige 7');
specifics_values_array.push('Prestige 7L');
specifics_values_array.push('Universal');
object_specific = {'title':'Compatible Product Line','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('China');
specifics_values_array.push('Japan');
object_specific = {'title':'Country of Manufacture','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('China');
specifics_values_array.push('Indonesia');
specifics_values_array.push('United States');
object_specific = {'title':'Country/Region of Manufacture','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Glossy');
specifics_values_array.push('Transparent');
object_specific = {'title':'Design/Finish','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Full-Length');
object_specific = {'title':'Dress Length','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Single');
object_specific = {'title':'Earpiece','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Earbud (In Ear)');
object_specific = {'title':'Earpiece Design','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Moisturizing');
specifics_values_array.push('SunScreen Protection');
object_specific = {'title':'Effect','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Alcohol-Free');
specifics_values_array.push('All Natural Ingredients');
specifics_values_array.push('Checkbook');
specifics_values_array.push('Cruelty-free/No Animal Testing');
specifics_values_array.push('Hypoallergenic');
specifics_values_array.push('Oil-Free');
specifics_values_array.push('Perfume-Free');
object_specific = {'title':'Features','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('In-Ear Only');
object_specific = {'title':'Fit Design','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Gluten Free');
object_specific = {'title':'Food Specifications','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Mascara');
object_specific = {'title':'Form','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Foam');
specifics_values_array.push('Lotion');
specifics_values_array.push('Pencil');
specifics_values_array.push('Powder');
specifics_values_array.push('Pressed Powder');
specifics_values_array.push('Stick');
object_specific = {'title':'Formulation','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('AEO');
specifics_values_array.push('Sparkling White Diamonds ');
object_specific = {'title':'Fragrance Name','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Body Spray');
object_specific = {'title':'Fragrance Type','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Cars');
specifics_values_array.push('Chicken Run');
specifics_values_array.push('Destiny');
specifics_values_array.push('Knockout Kings 2000');
specifics_values_array.push('NASCAR 99');
specifics_values_array.push('Skate or Die');
specifics_values_array.push('Super R.C. Pro-Am');
specifics_values_array.push('Waialae Country Club: True Golf Classics');
object_specific = {'title':'Game','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('For Him');
specifics_values_array.push('Girls');
specifics_values_array.push('Women');
object_specific = {'title':'Gender','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Puzzle');
specifics_values_array.push('Racing');
specifics_values_array.push('Shooter');
specifics_values_array.push('Sports');
object_specific = {'title':'Genre','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('100% Cotton');
specifics_values_array.push('100% Polyester');
specifics_values_array.push('65% Cotton, 35% Poly');
specifics_values_array.push('95% Cotton');
specifics_values_array.push('Canvas');
specifics_values_array.push('Cotton Blend');
specifics_values_array.push('Knit');
specifics_values_array.push('Leather');
specifics_values_array.push('Rigid Plastic');
specifics_values_array.push('TPU Plastic');
object_specific = {'title':'Material','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Benefiance');
specifics_values_array.push('Citrus WX445');
specifics_values_array.push('DSi XL');
specifics_values_array.push('Girl Next Door');
specifics_values_array.push('HTC');
specifics_values_array.push('Physicians Formula');
specifics_values_array.push('Pro 200');
specifics_values_array.push('Pro Long Wear');
specifics_values_array.push('Time Wise');
specifics_values_array.push('Unstoppable Eyeliner');
specifics_values_array.push('Visual Land');
object_specific = {'title':'Model','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('014633078657');
specifics_values_array.push('014633140217');
specifics_values_array.push('045496730161');
specifics_values_array.push('047875846913');
specifics_values_array.push('083717120025');
specifics_values_array.push('785138320656');
specifics_values_array.push('785138322278');
specifics_values_array.push('Candy Flex Rubber Transparent Protector Cover');
object_specific = {'title':'MPN','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Almonds');
object_specific = {'title':'Nut Type','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Casual');
specifics_values_array.push('Dressy');
specifics_values_array.push('Everyday');
object_specific = {'title':'Occasion','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Floral');
specifics_values_array.push('Paisley');
specifics_values_array.push('Plaids & Checks');
specifics_values_array.push('Polka Dot');
specifics_values_array.push('Solid');
object_specific = {'title':'Pattern','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('NES');
specifics_values_array.push('Nintendo 3DS XL');
specifics_values_array.push('Nintendo 64');
specifics_values_array.push('Nintendo Game Boy');
specifics_values_array.push('Nintendo Game Boy Advance');
specifics_values_array.push('Nintendo Game Boy Color');
specifics_values_array.push('Pro 200');
specifics_values_array.push('Sony PlayStation 4');
object_specific = {'title':'Platform','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Activision');
specifics_values_array.push('Eidos Interactive');
specifics_values_array.push('Nintendo');
specifics_values_array.push('Ultra');
object_specific = {'title':'Publisher','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('E - Everyone');
specifics_values_array.push('RP - Rating Pending');
specifics_values_array.push('T - Teen');
object_specific = {'title':'Rating','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('NTSC-C (China)');
specifics_values_array.push('NTSC-U/C (US/Canada)');
object_specific = {'title':'Region Code','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('1988');
specifics_values_array.push('1991');
specifics_values_array.push('1998');
specifics_values_array.push('1999');
specifics_values_array.push('2000');
specifics_values_array.push('2006');
specifics_values_array.push('2014');
object_specific = {'title':'Release Year','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Fall');
specifics_values_array.push('Spring');
specifics_values_array.push('Summer');
specifics_values_array.push('Winter');
object_specific = {'title':'Season','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('CHARGED BLACK');
specifics_values_array.push('Light to Medium');
specifics_values_array.push('NC25');
specifics_values_array.push('Pink');
object_specific = {'title':'Shade','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('0-3 Months');
specifics_values_array.push('1 oz. each');
specifics_values_array.push('1.7 oz');
specifics_values_array.push('18M');
specifics_values_array.push('Full Size');
specifics_values_array.push('S');
specifics_values_array.push('Travel Size');
object_specific = {'title':'Size','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('S');
object_specific = {'title':'Size (Women's)','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Regular');
object_specific = {'title':'Size Type','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('All Skin Types');
specifics_values_array.push('Dry Skin, Oily Skin');
object_specific = {'title':'Skin Type','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('HTCADR6330CASKCA043');
object_specific = {'title':'SKU','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Long Sleeve');
specifics_values_array.push('Short Sleeve');
object_specific = {'title':'Sleeve Length','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Cap Sleeve');
specifics_values_array.push('Long Sleeve');
object_specific = {'title':'Sleeve Style','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Curling, Volumizing, Lengthening, Thickening');
object_specific = {'title':'Special Properties','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Boxing');
specifics_values_array.push('Extreme Sports');
specifics_values_array.push('Golf');
specifics_values_array.push('Race');
object_specific = {'title':'Sports Sub-Genre','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Bikini Bottom');
specifics_values_array.push('Blouse');
specifics_values_array.push('Long Dress');
specifics_values_array.push('Trifold');
object_specific = {'title':'Style','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('7" Device');
specifics_values_array.push('9" Device');
specifics_values_array.push('Console & Games');
object_specific = {'title':'To Fit','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Almonds');
specifics_values_array.push('Body Spray');
specifics_values_array.push('Bronzer');
specifics_values_array.push('Cases');
specifics_values_array.push('Cleanser/Face Wash');
specifics_values_array.push('Cleansing Mask');
specifics_values_array.push('Crystal TPU Gel Skin');
specifics_values_array.push('Game Case/Sleeve');
specifics_values_array.push('Pro Folio Case');
specifics_values_array.push('Single');
object_specific = {'title':'Type','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('800768613746');
object_specific = {'title':'UPC','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
