document.write('<!--[if IE 9 ]>');
document.write('<style>');
document.write('</style>');
document.write('<![endif]-->');
document.write('<div class="row">');
document.write('<div class="col-sm-2"></div>');
document.write('<div class="col-sm-10" style="padding-right: 0px;">');
document.write('<div id="es_topLinksContainer">');
document.write('<div class="top-welcome-text visible-xs">Welcome to our online store!</div>');
document.write('<div class="ebay-basic-buttons  visible-md visible-lg">');
document.write('<div class="left">');
document.write('<a class="button-add-favorite-seller-link" href="">');
document.write('<div class="button-add-favorite-seller"></div>');
document.write('</a>');
document.write('</div>');
document.write('<div class="left">');
document.write('<a class="button-join-main-list-link" href="">');
document.write('<div class="button-join-main_list"></div>');
document.write('</a>');
document.write('</div>');
document.write('</div>');
document.write('</div>');
document.write('</div>');
document.write('</div>');
document.write('<div class="row">');
document.write('<div class="col-sm-12" id="es_header">');
document.write('<span id="logo-content-IE9"></span>');
document.write('<script type="text/javascript">');
document.write('include1("logo.js");');
document.write('</script>');
document.write('<script type="text/javascript">');
document.write('include1("header_background.js");');
document.write('</script>');
document.write('</div>');
document.write('</div>');
