document.write('<div class="row footer-custom-background footer-container">');
document.write('<div class="container">');
document.write('<div class="pull-right hidden-xs" id="es_footer">');
document.write('<div class="visible-lg visible-md visible-sm" id="es_formFooter">');
document.write('<form method="get" action="" class="store-home-url" name="search" id="es_searchform">');
document.write('<fieldset class="es_search">');
document.write('<input type="text" onfocus="if(this.value ==\'Search Our Ebay Store...\' ) this.value=\'\'" onblur="if(this.value==\'\') this.value=\'Search Our Ebay Store...\'" value="Search Our Ebay Store..." class="es_box" name="_nkw">');
document.write('<button title="Submit Search" class="es_btn" onclick="search()"><div class="button-search"></div></button>');
document.write('</fieldset>');
document.write('</form>');
document.write('</div>');
document.write('<div class="pull-right visible-lg visible-md visible-sm" id="es_formLinks">');
document.write('');
document.write('<script class="script" type="text/javascript" async>');
document.write('include1("footer_menu.js");');
document.write('</script>');
document.write('<ul class="footer-menu-content">');
document.write('</ul>');
document.write('</div>');
document.write('<div class="copyright"></div>');
document.write('</div>');
document.write('<div style="margin-bottom :5px; margin-top: 0px;margin-right: 25px;" class="pull-right">');
document.write('<div class="social-media-buttons">');
document.write('<script class="script" type="text/javascript" sync>');
document.write('include("social_media_buttons_parts.js");');
document.write('</script>');
document.write('</div>');
document.write('</div>');
document.write('</div>');
document.write('</div>');
document.write('<div class="powered-by">');
document.write('<a target="_blank" href="http://rockscripts.org" class="powered_link1">Powered by: <img class="rockscripts-logo-small" src="http://hosting.rockscripts.org/default/images/rockscripts-small.png"></a>');
document.write('</div>');
