document.write('<!--[if IE 9 ]>');
document.write('<style>');
document.write('</style>');
document.write('<![endif]-->');
document.write('<div class="row">');
document.write('<div class="col-sm-2">');
document.write('</div>');
document.write('<div class="col-sm-10" style="padding-right: 0px;" >');
document.write('<div id="es_topLinksContainer">');
document.write('<div class="social-media-buttons visible-lg visible-md visible-sm">');
document.write('</div>');
document.write('</div>');
document.write('</div>');
document.write('</div>');
document.write('<div class="row">');
document.write('<div class="col-sm-12" id="es_header">');
document.write('<div class="header-search-box visible-md visible-lg visible-sm">');
document.write('<div class="shopping-image">');
document.write('<a  class="shopping-icon-link" href="http://cart.payments.ebay.com.au/sc/view"></a>');
document.write('</div>');
document.write('<form class="navbar-form store-home-url" role="search" target="_top" method="get" action="">');
document.write('<span class="welcome-header-text">Welcome to our online store!</span><br>');
document.write('<a href="" class="link-top">Add to Favorite Seller</a> | <a href="" class="link-top">Join Mail List</a>');
document.write('<div class="input-group">');
document.write('<input type="text" id="nkw" name="_nkw"  class="form-control" placeholder="Search">');
document.write('<span class="input-group-btn">');
document.write('<input class="btn btn-default submit_search button-search search-icon-on-input" type="submit" value="">');
document.write('</span>');
document.write('</div>');
document.write('</form>');
document.write('</div>');
document.write('<span id="logo-content-IE9">');
document.write('</span>');
document.write('<script type="text/javascript">');
document.write('include1("logo.js");');
document.write('</script>');
document.write('<script type="text/javascript">');
document.write('include1("header_background.js");');
document.write('</script>');
document.write('</div>');
document.write('</div>');
