var specifics_array = new Array();
specifics_values_array = new Array();
specifics_values_array.push(' 7/16 inch (11mm)');
specifics_values_array.push('00g (10 mm)');
specifics_values_array.push('0g (8 mm)');
specifics_values_array.push('1/2 inch (12.7mm)');
specifics_values_array.push('14G');
specifics_values_array.push('14g (1.6 mm)');
specifics_values_array.push('18G');
specifics_values_array.push('18g (1 mm)');
specifics_values_array.push('7/16 inch (11mm)');
object_specific = {'title':'Gauge (Thickness)','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('One Size');
object_specific = {'title':'Size','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
