var specifics_array = new Array();
specifics_values_array = new Array();
specifics_values_array.push('Yes');
object_specific = {'title':'3G Connectivity','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Yes (via MiFi device, SOLD SEPARATELY)');
object_specific = {'title':'3G Usage (OPTIONAL)','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Accessory Kits');
specifics_values_array.push('Battery');
specifics_values_array.push('Datacable');
object_specific = {'title':'Accessory','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Amazon');
specifics_values_array.push('ASUS');
specifics_values_array.push('ASUS Google');
specifics_values_array.push('HTC');
specifics_values_array.push('Motorola');
specifics_values_array.push('NVIDIA');
specifics_values_array.push('OnePlus');
specifics_values_array.push('PowerA');
specifics_values_array.push('Samsung');
specifics_values_array.push('Samsung Google');
specifics_values_array.push('Spigen');
object_specific = {'title':'Brand','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('13.0 MP');
specifics_values_array.push('5.0 MP');
specifics_values_array.push('8.0 MP');
object_specific = {'title':'Camera','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('16 GB');
specifics_values_array.push('32 GB');
specifics_values_array.push('64 GB');
specifics_values_array.push('8 GB');
object_specific = {'title':'Capacity','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Black');
specifics_values_array.push('Charcoal Gray');
specifics_values_array.push('Dark Gray');
specifics_values_array.push('Dazzling White');
specifics_values_array.push('Gunmetal Gray');
specifics_values_array.push('Light Blue');
specifics_values_array.push('Light Gray');
specifics_values_array.push('Orange');
specifics_values_array.push('Pink');
specifics_values_array.push('Titanium Bronze');
specifics_values_array.push('White');
object_specific = {'title':'Colour','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('For Android');
specifics_values_array.push('For Apple');
specifics_values_array.push('For Asus');
specifics_values_array.push('For NVIDIA');
object_specific = {'title':'Compatible Brand','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Nexus 7');
object_specific = {'title':'Compatible Product Line','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('1 year');
object_specific = {'title':'Duration','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Fire 2014');
object_specific = {'title':'Family Line','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('3G');
specifics_values_array.push('4G Data Capable');
specifics_values_array.push('Anti-Scratch');
specifics_values_array.push('Bluetooth');
specifics_values_array.push('Built-In Front Camera');
specifics_values_array.push('Built-In Keyboard');
specifics_values_array.push('Built-In Rear Camera');
specifics_values_array.push('Colour Screen');
specifics_values_array.push('Email');
specifics_values_array.push('Expandable Memory');
specifics_values_array.push('External Memory');
specifics_values_array.push('Gaming');
specifics_values_array.push('Global Ready');
specifics_values_array.push('Glossy');
specifics_values_array.push('GPRS');
specifics_values_array.push('GPS');
specifics_values_array.push('GSM');
specifics_values_array.push('HD Recording');
specifics_values_array.push('Internet Browser');
specifics_values_array.push('Java enabled');
specifics_values_array.push('Matte/Anti-Glare');
specifics_values_array.push('MMS enabled');
specifics_values_array.push('MP3 Player');
specifics_values_array.push('PC Sync');
specifics_values_array.push('Polyphonic ringtones');
specifics_values_array.push('Primary Camera');
specifics_values_array.push('Washable');
object_specific = {'title':'Features','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('1.3 megapixel');
specifics_values_array.push('1.6 MP');
specifics_values_array.push('1.9 megapixel');
specifics_values_array.push('2.1 MP');
specifics_values_array.push('5MP');
specifics_values_array.push('VGA');
object_specific = {'title':'Front Camera Mega Pixel','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('16 GB');
specifics_values_array.push('32 GB');
specifics_values_array.push('8 GB');
object_specific = {'title':'Hard Drive Capacity','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Bluetooth');
specifics_values_array.push('Micro HDMI');
specifics_values_array.push('USB');
object_specific = {'title':'Hardware Connectivity','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Wi-Fi');
specifics_values_array.push('Wi-Fi + 4G');
object_specific = {'title':'Internet Connectivity','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Hard Polycarbonate + TPU');
specifics_values_array.push('Silicone/Gel/Rubber');
specifics_values_array.push('TPU');
object_specific = {'title':'Material','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('One A0001');
specifics_values_array.push('XT1032');
specifics_values_array.push('XT1063');
object_specific = {'title':'Model','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('00384NAECOM');
specifics_values_array.push('00385NAECOM');
specifics_values_array.push('00505NARTL');
specifics_values_array.push('00506NARTL');
specifics_values_array.push('90-XB3TOKSL00080');
specifics_values_array.push('90-XB3TOKSL00180-');
specifics_values_array.push('90-XB3TOKSL001M0-');
specifics_values_array.push('90-XB3TOKSL001N0-');
specifics_values_array.push('90-XB3TOKSL001P0');
specifics_values_array.push('90-XB3TOKSL001Q0-');
specifics_values_array.push('90-XB3XOKDS00030');
specifics_values_array.push('90XB00KP-BSC010');
specifics_values_array.push('99HZF001-00');
specifics_values_array.push('99HZF002-00');
specifics_values_array.push('99HZF003-00');
specifics_values_array.push('99HZF004-00');
specifics_values_array.push('B00IKPW0UA');
specifics_values_array.push('B00IKPYKWG');
specifics_values_array.push('B00KC6I06S');
specifics_values_array.push('B00KC6IUO0');
specifics_values_array.push('CPFA123252-01');
specifics_values_array.push('CPFA130322-01');
specifics_values_array.push('GT-P8110HAEXAR');
specifics_values_array.push('GTP8110HAGR');
specifics_values_array.push('HTCM8DEV');
specifics_values_array.push('NEXUS7-ASUS-2B16');
specifics_values_array.push('NEXUS7-ASUS-2B32');
specifics_values_array.push('NEXUS7-ASUS-2B32-LTE');
specifics_values_array.push('NV940817612500000');
specifics_values_array.push('NV940817612500100');
specifics_values_array.push('NV945125702500000');
specifics_values_array.push('OPO16GBWH');
specifics_values_array.push('OPO64GBBL');
specifics_values_array.push('OPO64GBWH');
specifics_values_array.push('SM-T700NTSAXAR');
specifics_values_array.push('SM-T700NZWAXAR');
specifics_values_array.push('SM-T800NTSAXAR');
object_specific = {'title':'MPN','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Android');
specifics_values_array.push('Android 4.4 KitKat');
specifics_values_array.push('Android 4.4.x KitKat');
specifics_values_array.push('Android 5.0 Lollipop');
specifics_values_array.push('CyanogenMod 11S (Android 4.x)');
object_specific = {'title':'Operating System','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('1.2 GHz');
specifics_values_array.push('1.5 GHz');
specifics_values_array.push('1.7 GHz');
specifics_values_array.push('1.9 GHz + 1.3 GHz');
specifics_values_array.push('Dual-core 1.5 GHz &amp; dual-core 1.2 GHz');
specifics_values_array.push('Nvidia Tegra K1 CPU Dual-core 2.3 GHz Denver');
object_specific = {'title':'Processor Speed','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('1 GB');
specifics_values_array.push('2 GB');
specifics_values_array.push('3 GB');
object_specific = {'title':'RAM','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('2 MP');
specifics_values_array.push('5 megapixel');
specifics_values_array.push('5MP');
specifics_values_array.push('8 MP');
specifics_values_array.push('8.0 MP');
object_specific = {'title':'Rear Camera Mega Pixel','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('10&quot;');
specifics_values_array.push('10.5&quot;');
specifics_values_array.push('6&quot;');
specifics_values_array.push('7&quot;');
specifics_values_array.push('8&quot;');
specifics_values_array.push('8.4');
specifics_values_array.push('8.9&quot;');
object_specific = {'title':'Screen Size','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('No');
specifics_values_array.push('Yes');
object_specific = {'title':'Serviced In India','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Single Sim');
object_specific = {'title':'Sim Type','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Bar');
specifics_values_array.push('Flip Cover/Case');
specifics_values_array.push('Folding Folio Case');
specifics_values_array.push('Smartphone');
specifics_values_array.push('Touch');
specifics_values_array.push('TPU');
specifics_values_array.push('Wireless Controller');
object_specific = {'title':'Type','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('International Warranty');
specifics_values_array.push('Manufacturer Warranty');
specifics_values_array.push('No Warranty');
specifics_values_array.push('Seller Warranty');
object_specific = {'title':'Warranty','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('To &amp; Fro International Shipping Charges Applicable');
specifics_values_array.push('Valid in US Only');
object_specific = {'title':'Warranty Conditions','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('1 Year Manufacturer Warranty');
specifics_values_array.push('International Manufacturer Warranty');
object_specific = {'title':'Warranty Details','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
specifics_values_array = new Array();
specifics_values_array.push('Repair');
object_specific = {'title':'Warranty Service','custom_title':'','specifics_values':specifics_values_array};
specifics_array.push(object_specific);
